### ISSUE TITLE
Trouble to use "node src/assembler"

### ISSUE THREAD

**Issue by hlide** [francisrstokes/16bitjs#31]
Under Windows 10 64-bit, latest version of Node.js: `v8.2.1`.

I'm not familiar with Node.js as it is pretty recent I'm using it at work.

So once Node.js installed, I made `npm install` and nothing else.

I tried this: `C:\Dev\16bitjs>node src\assembler -i asm\factorial.asm -o bin\factorial.bin`

And I got:
```
C:\Dev\16bitjs\src\assembler\preprocessor\get-data-table.js:70
      throw new Error`Unsupported data declaraction:\n${cur}\nExiting...`);
                                                                         ^

SyntaxError: Unexpected token )
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Dev\16bitjs\src\assembler\preprocessor\index.js:3:22)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
```

Not sure if the issue is due to my way to install Node.js.

**Comment by hlide** [comment]
Ok I fixed it with the missing `(` and got:
```
Read 60 instructions, including labels.
Expanded to 55, including labels.
Removed labels. Final instruction count: 52/65535
{ '.equals': { type: 2, size: 8, address: 52, data: ' * 1 = ' },
  '.counter': { type: 0, size: 1, address: 60, data: 8 },
  '.result': { type: 0, size: 1, address: 61, data: 8 },
  '.times': { type: 2, size: 4, address: 62, data: ' * ' } }
Successfully assembled to binary file bin\factorial.bin
```

**Comment by francisrstokes** [comment]
No there was an error in my code. Pushed a fix
